pluginManagement {
    repositories {
        maven { url = "https://maven.aliyun.com/repository/gradle-plugin" }
        // 使用 possible‑triangle 镜像代替官方 neoforge plugins
        maven { url = "https://registry.somethingcatchy.net/repository/maven-public/" }
        maven {
            url "https://modmaven.dev/"
            metadataSources {
                artifact()
            }
        }
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    // ❌ 原来的，会报错
    // repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    // ✅ 修改为这个
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    repositories {
        repositories.clear()
        maven {
            url "https://modmaven.dev/"
            metadataSources {
                artifact()
            }
        }
        maven { url = "https://maven.aliyun.com/repository/public" }

        maven { url = "https://neoforged.forgecdn.net/releases" }
        maven { url = "https://neoforged.forgecdn.net/snapshots" }
        maven { url = "https://neoforged.forgecdn.net/mojang-meta" }

        // 官方兜底，网络好时打开
        // maven { url = "https://maven.neoforged.net/releases" }
        // maven { url = "https://maven.neoforged.net/snapshots" }
        // maven { url = "https://maven.neoforged.net/mojang-meta" }

        maven { url = "https://libraries.minecraft.net" }
        mavenCentral()
    }
}